#!/usr/bin/env python3
"""
Page Generator for MagicPencil
Generates static HTML pages for all coloring images and categories.
Run from scripts/tools/ OR from the project root — script auto-detects location.

Output:
  color/{category}/{slug}.html    — one page per coloring image
  categories/{category}.html      — one page per category
"""

import os
import re
import json
import sys
from pathlib import Path

# ── Path setup ────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = (SCRIPT_DIR / '../..' ).resolve()

BASE_URL = "https://magicpencil.fun"

# Input files
CATALOG_FILE     = PROJECT_ROOT / 'js' / 'data' / 'image-catalog.js'
METADATA_FILE    = PROJECT_ROOT / 'js' / 'data' / 'category-metadata.js'
CONTENT_FILE     = SCRIPT_DIR / 'page-content.json'
DESKTOP_TEMPLATE = SCRIPT_DIR / 'templates' / 'page-desktop.html'
CATEGORY_TEMPLATE = SCRIPT_DIR / 'templates' / 'page-category.html'

# Output directories
OUTPUT_COLORING  = PROJECT_ROOT / 'color'
OUTPUT_CATEGORIES = PROJECT_ROOT / 'categories'

# Category display names (fallback if metadata parse fails)
CATEGORY_NAMES = {
    'alphabets': 'Alphabets', 'animals': 'Animals', 'princess': 'Princess',
    'unicorns': 'Unicorns', 'vehicles': 'Vehicles', 'food': 'Food',
    'nature': 'Nature', 'holidays': 'Holidays', 'ocean': 'Ocean',
    'fantasy': 'Fantasy', 'shapes': 'Shapes', 'flowers': 'Flowers'
}

# ── ANSI helpers ──────────────────────────────────────────────────────────────
def ok(msg):   print(f"\033[92m[OK]\033[0m {msg}")
def info(msg): print(f"\033[94m[INFO]\033[0m {msg}")
def warn(msg): print(f"\033[93m[WARN]\033[0m {msg}")
def err(msg):  print(f"\033[91m[ERROR]\033[0m {msg}")

# ── Parsers ───────────────────────────────────────────────────────────────────

def parse_image_catalog():
    """Parse js/data/image-catalog.js and return list of image dicts."""
    content = CATALOG_FILE.read_text(encoding='utf-8')
    pattern = (
        r"\{\s*id:\s*'([^']+)',\s*category:\s*'([^']+)',\s*"
        r"name:\s*'([^']+)',\s*filename:\s*'([^']+)',\s*"
        r"difficulty:\s*'([^']+)',\s*regions:\s*(\d+)\s*\}"
    )
    images = []
    for m in re.finditer(pattern, content, re.DOTALL):
        images.append({
            'id':         m.group(1),
            'category':   m.group(2),
            'name':       m.group(3),
            'filename':   m.group(4),
            'difficulty': m.group(5),
            'regions':    int(m.group(6))
        })
    info(f"Parsed {len(images)} images from image-catalog.js")
    return images


def parse_category_metadata():
    """
    Parse js/data/category-metadata.js.
    Returns dict keyed by category ID with name, title, description, contentDescription.
    """
    content = METADATA_FILE.read_text(encoding='utf-8')
    result = {}

    for cat_id in CATEGORY_NAMES:
        # Find the start of this category block in the JS object
        # Pattern: "    animals: {" or "    alphabets: {"
        block_start_pattern = rf'\n\s+{re.escape(cat_id)}:\s*\{{'
        start_m = re.search(block_start_pattern, content)
        if not start_m:
            warn(f"Category block not found for: {cat_id}")
            continue

        # Take a slice of content after the block start for field extraction
        # 25000 chars is enough to capture the contentDescription template literal
        block = content[start_m.start():]

        name_m  = re.search(r"name:\s*'([^']+)'", block[:500])
        title_m = re.search(r"title:\s*'([^']+)'", block[:500])
        desc_m  = re.search(r"description:\s*'([^']+)'", block[:500])
        # contentDescription uses a backtick template literal
        cdesc_m = re.search(r'contentDescription:\s*`([\s\S]*?)`', block[:30000])

        result[cat_id] = {
            'name':               name_m.group(1) if name_m else CATEGORY_NAMES[cat_id],
            'title':              title_m.group(1) if title_m else f'{CATEGORY_NAMES[cat_id]} Coloring Pages | MagicPencil',
            'description':        desc_m.group(1) if desc_m else f'Free {CATEGORY_NAMES[cat_id].lower()} coloring pages for kids.',
            'contentDescription': cdesc_m.group(1).strip() if cdesc_m else ''
        }

    ok(f"Parsed metadata for {len(result)} categories")
    return result


def load_custom_content():
    """Load optional page-content.json for custom SEO overrides."""
    if not CONTENT_FILE.exists():
        warn("page-content.json not found — using auto-generated content only")
        return {}
    data = json.loads(CONTENT_FILE.read_text(encoding='utf-8'))
    ok(f"Loaded custom content for {len(data)} images")
    return data


def load_fun_facts():
    """Load fun-facts.json generated by generate-fun-facts.py."""
    fun_facts_file = SCRIPT_DIR / 'fun-facts.json'
    if not fun_facts_file.exists():
        warn("fun-facts.json not found — run generate-fun-facts.py to create it")
        return {}
    data = json.loads(fun_facts_file.read_text(encoding='utf-8'))
    ok(f"Loaded {len(data)} fun facts")
    return data


FUN_FACT_HTML = """\
    <section class="fun-fact-section">
        <div class="fun-fact-inner">
            <span class="fun-fact-icon">💡</span>
            <div class="fun-fact-text">
                <h3 class="fun-fact-heading">Did You Know?</h3>
                {paragraphs}
            </div>
        </div>
    </section>"""


def build_fun_fact_section(fact_text):
    """Wrap each paragraph in <p> tags and return the full section HTML."""
    paragraphs = '\n                '.join(
        f'<p>{p.strip()}</p>'
        for p in fact_text.strip().split('\n')
        if p.strip()
    )
    return FUN_FACT_HTML.format(paragraphs=paragraphs)

# ── Content auto-generators ───────────────────────────────────────────────────

def title_case(name):
    """Title-case an image name: 'honey-bee' -> 'Honey Bee', 'A Apple' -> 'A Apple'."""
    return name.title()


def auto_content(image):
    """Generate SEO content from image metadata when no custom entry exists."""
    name = image['name']
    cat  = image['category']
    cat_name = CATEGORY_NAMES.get(cat, cat.title())

    title       = f"{name} Coloring Page for Kids — Free Online | MagicPencil"
    description = (
        f"Color a {name.lower()} online for free! Tap to fill with colors, gradients, "
        f"and patterns. Perfect for kids ages 2–12. Print or download your artwork."
    )
    h1    = f"{name} Coloring Page"
    blurb = (
        f"Bring this {name.lower()} to life with your favorite colors! "
        f"Tap any area to fill it instantly. Try solid colors, rainbow gradients, "
        f"or fun patterns like dots and stars. When you're done, download your artwork or print it out."
    )
    return {'title': title, 'description': description, 'h1': h1, 'blurb': blurb}


def image_id_to_slug(image_id, category):
    """'animals-honey-bee' + 'animals' → 'honey-bee'."""
    prefix = category + '-'
    if image_id.startswith(prefix):
        return image_id[len(prefix):]
    return image_id


def clean_url(category, slug):
    return f"{BASE_URL}/color/{category}/{slug}.html"


def category_url(category):
    return f"{BASE_URL}/categories/{category}.html"

# ── Schema builders ───────────────────────────────────────────────────────────

def make_breadcrumb_json_coloring(image, cat_name, canonical, h1):
    data = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home",     "item": f"{BASE_URL}/"},
            {"@type": "ListItem", "position": 2, "name": cat_name,   "item": category_url(image['category'])},
            {"@type": "ListItem", "position": 3, "name": h1,         "item": canonical}
        ]
    }
    return json.dumps(data, indent=2, ensure_ascii=False)


def make_image_schema_json(image, canonical, description):
    encoded = image['filename'].replace(' ', '%20')
    data = {
        "@context": "https://schema.org",
        "@type": "ImageObject",
        "name": image['name'],
        "contentUrl": f"{BASE_URL}/images/{image['category']}/{encoded}",
        "description": description,
        "url": canonical
    }
    return json.dumps(data, indent=2, ensure_ascii=False)


def make_breadcrumb_json_category(cat_id, cat_name, canonical):
    data = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home",     "item": f"{BASE_URL}/"},
            {"@type": "ListItem", "position": 2, "name": cat_name,   "item": canonical}
        ]
    }
    return json.dumps(data, indent=2, ensure_ascii=False)

# ── Page generators ───────────────────────────────────────────────────────────

def generate_coloring_page(image, template, custom_content, fun_facts):
    slug     = image_id_to_slug(image['id'], image['category'])
    canonical = clean_url(image['category'], slug)
    cat_name = CATEGORY_NAMES.get(image['category'], image['category'].title())
    cat_url  = f"/categories/{image['category']}.html"

    # Use custom content if available, otherwise auto-generate
    c = custom_content.get(image['id']) or auto_content(image)
    title       = c['title']
    description = c['description']
    h1          = c['h1']
    blurb       = c['blurb']

    breadcrumb_json  = make_breadcrumb_json_coloring(image, cat_name, canonical, h1)
    image_schema_json = make_image_schema_json(image, canonical, description)

    # Fun fact section — present if fact exists, empty string otherwise
    fact_text = fun_facts.get(image['id'], '')
    fun_fact_section = build_fun_fact_section(fact_text) if fact_text else ''

    html = template
    html = html.replace('{{TITLE}}',            title)
    html = html.replace('{{DESCRIPTION}}',      description)
    html = html.replace('{{CANONICAL}}',        canonical)
    html = html.replace('{{H1}}',               h1)
    html = html.replace('{{H1_LOWER}}',         h1.lower())
    html = html.replace('{{BLURB}}',            blurb)
    html = html.replace('{{IMAGE_ID}}',         image['id'])
    html = html.replace('{{CATEGORY}}',         image['category'])
    html = html.replace('{{CATEGORY_NAME}}',    cat_name)
    html = html.replace('{{CATEGORY_URL}}',     cat_url)
    html = html.replace('{{BREADCRUMB_JSON}}',  breadcrumb_json)
    html = html.replace('{{IMAGE_SCHEMA_JSON}}', image_schema_json)
    html = html.replace('{{FUN_FACT_SECTION}}', fun_fact_section)

    return html, slug


def generate_category_page(cat_id, metadata, template):
    cat_name  = metadata.get('name', CATEGORY_NAMES.get(cat_id, cat_id.title()))
    canonical = category_url(cat_id)
    title     = metadata.get('title', f'{cat_name} Coloring Pages | MagicPencil')
    desc      = metadata.get('description', f'Free {cat_name.lower()} coloring pages for kids.')
    content   = metadata.get('contentDescription', '')

    breadcrumb_json = make_breadcrumb_json_category(cat_id, cat_name, canonical)

    html = template
    html = html.replace('{{TITLE}}',                title)
    html = html.replace('{{DESCRIPTION}}',          desc)
    html = html.replace('{{CANONICAL}}',            canonical)
    html = html.replace('{{CATEGORY_ID}}',          cat_id)
    html = html.replace('{{CATEGORY_NAME}}',        cat_name)
    html = html.replace('{{CONTENT_DESCRIPTION}}',  content)
    html = html.replace('{{BREADCRUMB_JSON}}',      breadcrumb_json)

    return html

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  MagicPencil — Page Generator")
    print("=" * 60)

    # Validate inputs
    for path, label in [
        (CATALOG_FILE,      'image-catalog.js'),
        (METADATA_FILE,     'category-metadata.js'),
        (DESKTOP_TEMPLATE,  'templates/page-desktop.html'),
        (CATEGORY_TEMPLATE, 'templates/page-category.html')
    ]:
        if not path.exists():
            err(f"Required file not found: {path}")
            sys.exit(1)

    # Load inputs
    images         = parse_image_catalog()
    cat_metadata   = parse_category_metadata()
    custom_content = load_custom_content()
    fun_facts      = load_fun_facts()
    desktop_tpl    = DESKTOP_TEMPLATE.read_text(encoding='utf-8')
    category_tpl   = CATEGORY_TEMPLATE.read_text(encoding='utf-8')

    if not images:
        err("No images found in catalog — aborting.")
        sys.exit(1)

    # ── Generate coloring pages ──────────────────────────────────────────────
    print()
    info("Generating coloring pages...")
    coloring_count = 0
    categories_seen = set()

    for image in images:
        html, slug = generate_coloring_page(image, desktop_tpl, custom_content, fun_facts)
        cat = image['category']
        categories_seen.add(cat)

        out_dir = OUTPUT_COLORING / cat
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / f"{slug}.html"
        out_file.write_text(html, encoding='utf-8')
        coloring_count += 1

    ok(f"Generated {coloring_count} coloring pages -> color/")

    # ── Generate category pages ──────────────────────────────────────────────
    print()
    info("Generating category pages...")
    cat_count = 0
    OUTPUT_CATEGORIES.mkdir(parents=True, exist_ok=True)

    for cat_id in sorted(categories_seen | set(cat_metadata.keys())):
        meta = cat_metadata.get(cat_id, {
            'name': CATEGORY_NAMES.get(cat_id, cat_id.title()),
            'title': f'{CATEGORY_NAMES.get(cat_id, cat_id.title())} Coloring Pages | MagicPencil',
            'description': f'Free {cat_id} coloring pages for kids.',
            'contentDescription': ''
        })
        html = generate_category_page(cat_id, meta, category_tpl)
        out_file = OUTPUT_CATEGORIES / f"{cat_id}.html"
        out_file.write_text(html, encoding='utf-8')
        cat_count += 1

    ok(f"Generated {cat_count} category pages -> categories/")

    # ── Summary ──────────────────────────────────────────────────────────────
    print()
    print("=" * 60)
    print(f"  Done! Generated {coloring_count + cat_count} pages total")
    print(f"  * {coloring_count} coloring pages (color/<category>/<slug>.html)")
    print(f"  * {cat_count} category pages (categories/<category>.html)")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Open color/animals/elephant.html in your browser — verify it loads")
    print("  2. Check that the image is colorable (JS reads data-image-id from <body>)")
    print("  3. Then run the full automation: run-svg-automation.bat")


if __name__ == '__main__':
    main()
